services:
  knacxtest:
    container_name: knacxtest
    image: node:22-bookworm-slim
    env_file: ../.env
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached
    ports:
      - 8080:8080

    networks:
      - knacxnetwork
    command: sleep infinity

  knacxtestdb:
    container_name: knacxtestdb
    build:
      context: ./
      dockerfile: postgres.Dockerfile
      args:
        - POSTGRES_USER:$POSTGRES_USER
        - POSTGRES_PASSWORD:$POSTGRES_PASSWORD
        - POSTGRES_DB:$POSTGRES_DB
    env_file: ../.env
    ports:
    - 5432:5432

    networks:
      - knacxnetwork

networks:
  knacxnetwork:
    driver: bridge