services:
  knacxtest:
    container_name: knacxtest
    image: node:22-bookworm-slim
    env_file: ../.env
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached
    ports:
      - 8080:8080

    networks:
      - knacxnetwork
    command: sleep infinity

  knacxtestdb:
    container_name: knacxtestdb
    image: postgres
    env_file: ../.env
    ports:
      - 5432:5432

    volumes: 
      - ./init.sh:/docker-entrypoint-initdb.d/init_db.sh

    networks:
      - knacxnetwork


networks:
  knacxnetwork:
    driver: bridge